# Generated by Django 5.0 on 2023-12-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='homeImage',
            field=models.ImageField(default='null', upload_to='destination'),
        ),
    ]
