# Generated by Django 5.0 on 2023-12-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_destination_homeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='homeImage',
            field=models.ImageField(default='null', upload_to='admin/img'),
        ),
    ]
